// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALKPMWw3fmUWK99p60b1KOqzi9MIyzBLQ',
    appId: '1:142213387273:web:bd7a1fe2cfdd2a1a0f54d8',
    messagingSenderId: '142213387273',
    projectId: 'bai-tap-tuan-5',
    authDomain: 'bai-tap-tuan-5.firebaseapp.com',
    storageBucket: 'bai-tap-tuan-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXQbvBG7iynbK93-Wz6HoFP-OnC1teQ_4',
    appId: '1:142213387273:android:a766f963fc83fecc0f54d8',
    messagingSenderId: '142213387273',
    projectId: 'bai-tap-tuan-5',
    storageBucket: 'bai-tap-tuan-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4bPJL2r56vofL4jeCh-du1fev4HX4s9c',
    appId: '1:142213387273:ios:7cb425770ea813400f54d8',
    messagingSenderId: '142213387273',
    projectId: 'bai-tap-tuan-5',
    storageBucket: 'bai-tap-tuan-5.appspot.com',
    iosClientId: '142213387273-svr0tqgh00senkd55o2ho0rbiqv0artq.apps.googleusercontent.com',
    iosBundleId: 'com.example.btTuan5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4bPJL2r56vofL4jeCh-du1fev4HX4s9c',
    appId: '1:142213387273:ios:7cb425770ea813400f54d8',
    messagingSenderId: '142213387273',
    projectId: 'bai-tap-tuan-5',
    storageBucket: 'bai-tap-tuan-5.appspot.com',
    iosClientId: '142213387273-svr0tqgh00senkd55o2ho0rbiqv0artq.apps.googleusercontent.com',
    iosBundleId: 'com.example.btTuan5',
  );
}
